# Generated by Django 5.2.16 on 2026-07-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código de la Marca')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código SAP')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('origin', models.CharField(choices=[('VENTA', 'Venta'), ('COMPRA', 'Compra')], max_length=20, verbose_name='Origen')),
                ('family', models.CharField(max_length=100, verbose_name='Familia')),
                ('subfamily', models.CharField(max_length=100, verbose_name='Subfamilia')),
                ('is_truck_mounted', models.BooleanField(default=False, verbose_name='Sobre Camión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.brand', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
