# Generated by Django 5.2.16 on 2026-07-28 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_cost_usd', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Unitario (USD)')),
                ('requested_by', models.CharField(max_length=150, verbose_name='Solicitado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Solicitud')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='core.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Solicitud de Compra',
                'verbose_name_plural': 'Solicitudes de Compra',
            },
        ),
    ]
