# Generated by Django 5.2.16 on 2026-07-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_purchaserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='decision_note',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios del Planificador'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='planned_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mes Compra Planificado'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado para Compra'), ('RECHAZADO', 'Rechazado (Sobrestock)')], default='PENDIENTE', max_length=20, verbose_name='Estado S&OP'),
        ),
    ]
